per_page: 8

filter_types:
  - "not_learn"
  - "learned"
  - "true_words"
  - "false_words"
  - "_all"
number_words_per_lesson: 20
number_words_min: 2
word_size: 2
activity_type:
  learned: 1
  learning: 2
  follow: 3
  unfollow: 4
image:
  size: "250x250"
  medium: "50X50"
word_size: 2

